### ISSUE TITLE
请求添加GitHub Workflow

### ISSUE THREAD

**Issue by LaureatePoet** [HFUTTUG/HFUT_Thesis#13]
* 测试编译 `main.tex`
* 测试编译 `hfutthesis-doc.tex`
* 当dev分支merge到master分支时，自动release：describe通过`changelog.md`获得，Assets：包含 `hfutthesis-doc.pdf`及master分支源码

**Comment by ter-li** [comment]
## Fineshed

> 测试编译 main.tex
> 测试编译 hfutthesis-doc.tex

* test passed on ```ubuntu-latest```
* PR @ ```dev```

## TODO

* add CI test on other platforms, i.e. macOS(MacTex), win(TexLive)
* add CI for auto-tagging, trigged when push to ```master``` branch

**Comment by ter-li** [comment]
Close: 

* add CI for auto release, trigger activates when pushing tagging named v*
