### ISSUE TITLE
去除最终生成的pdf空白页

### ISSUE THREAD

**Issue by XuYuQuan0713** [HFUTTUG/HFUT_Thesis#23]
## 检查
- [ ] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统： Windows 10
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型： professional

## 描述问题
**生成pdf中空白页的问题**

截图：
![QQ截图20220422172331](https://user-images.githubusercontent.com/67585051/164677561-3beb311d-d93d-4cba-a194-220842cf58be.jpg)

## 解决方案：
在hfutsetup.tex文件中加入如下代码：
```TeX
\let\cleardoublepage\clearpage%%去除空白页
```

**Comment by zepinglee** [comment]
空白页是为了方便打印的。
