### ISSUE TITLE
frontmatter部分的底部建议加上页码，用大写罗马数字

### ISSUE THREAD

**Issue by hfut-xyc** [HFUTTUG/HFUT_Thesis#27]
如题

**Comment by LaureatePoet** [comment]
## 检查
- [ ] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
《合肥工业大学研究生学位论文写作规范》的 xx 文档的第xx页要求……而模板编译的结果是……

截图：


复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{hfutthesis}
\begin{document}
abc
\end{document}
```

> 
> 如果发现模板有问题，请按照以下步骤操作：
> 
> 1. 阅读学校的标准，判断是否符合学校的要求；
> 2. 阅读 [常见问题 FAQ](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)；
> 3. 将 TeX 发行版和宏包升级到最新，并且将模板升级到 Github 上最新版本，
> 查看问题是否已经修复；
> 4. 在 [GitHub Issues](https://github.com/HFUTTUG/HFUT_Thesis/issues)
> 中搜索该问题的关键词；
> 5. 在 [GitHub Issues](https://github.com/HFUTTUG/HFUT_Thesis/issues)
> 中提出新 issue，并回答以下问题：
>     - 使用了什么版本的 TeX Live / MacTeX / MiKTeX ？
>     - 具体的问题是什么？
>     - 正确的结果应该是什么样的？
>     - 是否应该附上相关源码或者截图？
> 
> 如果导师或者院系在格式上有额外的要求，请将老师的邮件转发给模板作者。
> 作者会考虑增加接口以便修改格式。

**Comment by LaureatePoet** [comment]
[合肥工业大学毕业设计手册2022.1.pdf](https://github.com/HFUTTUG/HFUT_Thesis/files/8790494/2022.1.pdf)
