### ISSUE TITLE
macOS下华文系列字体可能导致复制时乱码

### ISSUE THREAD

**Issue by thelastlin** [HFUTTUG/HFUT_Thesis#28]
## 检查
- [x] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [x] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 12.3.1
- TeX 发行版：MacTeX 2022 / TeX Live 2022
- 模板类型： bachelor

## 描述问题
Macintosh平台使用的字体可能导致标题、章标题、一级节标题等部分在PDF阅读器内复制乱码。
在其他平台编译，或是手动指定使用Noto系列字体则无此问题。

**Comment by zepinglee** [comment]
传一份复制出错的 PDF？另外你是用的哪个 PDF 阅读器？

**Comment by thelastlin** [comment]
> 传一份复制出错的 PDF？

[点此](https://github.com/HFUTTUG/HFUT_Thesis/files/8687141/example.pdf)


> 另外你是用的哪个 PDF 阅读器？

测试过的PDF阅读器有macOS平台上的Preview.app、Firefox、Edge，Windows平台上的Firefox、Edge，均表现出一致的乱码问题。

**Comment by LaureatePoet** [comment]
`ustcthesis` 似乎也有同样的BUG 😮

**Comment by thelastlin** [comment]
> 我能复现这个问题，似乎是字体本身的 cmap 坏了。MWE：
> 
> ```
> \documentclass{article}
> \usepackage{xeCJK}
> \setCJKsansfont{Heiti SC Light}
> % \setCJKsansfont{STHeitiSC-Light}
> \begin{document}
> \sffamily 劳伦衣普桑
> \end{document}
> ```
成功复现。

> @thelastlin 另外可以打开 Font Book 确认一下 Heiti SC（黑体-简） 的版本是 `17.0d1e2; 2021-06-23` 吗？

字体版本一致。

**Comment by zepinglee** [comment]
嗯，那就是 macOS 提供的字体 bug 了，在模板这边没什么办法解决。

**Comment by m13673737851** [comment]
1、Mac安装 字体SimSun, Simhei, Fangsong, Kaiti ；
2、在main.tex中修改参数\documentclass[degree=bachelor,fontset=windows]{hfutthesis}即可。

尝试后解决MacOS编译后一二级标题无法复制的情况。

**Comment by LaureatePoet** [comment]
具体解决方案可以参考楼上。
或者参考 [ustcthesis#358](https://github.com/ustctug/ustcthesis/issues/358)。
