### ISSUE TITLE
Mac系统下‘参考文献’几个字复制会成为0x00，导致查重无法忽略参考文献

### ISSUE THREAD

**Issue by luyi404** [HFUTTUG/HFUT_Thesis#29]
## 检查
- [x] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [x] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 12.3.1
- TeX 发行版：MacTeX 2022
- 模板类型：bachelor

## 描述问题
在生成pdf后，参考文献部分的标题不能被其他地方识别，即不能复制出去，复制出去为乱码，但是显示无任何异常。

导致在查重时发现不了这几个字，引用一片红。

截图：
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/46224920/169091657-f90cb0fd-302e-4fcd-83e4-09fd2f80813b.png">

复现上述问题的代码：
可以尝试用mac下编译一次尝试复现，win下好像未出现这个问题

用的默认代码
```TeX
\bibliography{bib/hfut}
```

**Comment by LaureatePoet** [comment]
目前模板这边不能做出什么帮助。只能推荐使用win编译。

**Comment by HowardZorn** [comment]
应该可以通过安装中易宋体或者使用MacTeX应该自带的Fandol来解决<del>，或者使用Source Han Serif（思源宋体，听说这一届已经有人使用，但是其字体风格与中国的宋体差别有些大，大胆的话可以试试）</del>。

另外，根据你的参考文献列表，推荐计算机的bibtex在dblp.org上找到对应的会议论文，不然全是arXiv preprint……

**Comment by luyi404** [comment]
okok, 我用overleaf重新弄了
