### ISSUE TITLE
如何将封面系名称改为学院名称呢

### ISSUE THREAD

**Issue by cyinen** [HFUTTUG/HFUT_Thesis#31]
## 检查
- [ ] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
《合肥工业大学研究生学位论文写作规范》的 xx 文档的第xx页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{hfutthesis}
\begin{document}
abc
\end{document}
```

**Comment by l1teng** [comment]
你可以修改这部分代码，

https://github.com/HFUTTUG/HFUT_Thesis/blob/32dd5e2fd21fd9918003f62a721828f35e5fe43a/hfutthesis.cls#L1688-L1690

将代码块中``系名称``修改为``学院名称``。

**Comment by l1teng** [comment]
题外话，你可以提供一下学校最新的模板截图，如果相关内容需要更新，我们将对这部分进行修正。

**Comment by liyiwei979621500** [comment]
@l1teng 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/16919236/170461042-52b75d9e-1bed-4f20-8dc5-b53379e589b9.png">

<img width="522" alt="image" src="https://user-images.githubusercontent.com/16919236/170460981-40764b1b-20d6-42b2-9e1d-983fe6ae206e.png">
在毕设系统中下载的模版

**Comment by liyiwei979621500** [comment]
> 你可以修改这部分代码，
> 
> https://github.com/HFUTTUG/HFUT_Thesis/blob/32dd5e2fd21fd9918003f62a721828f35e5fe43a/hfutthesis.cls#L1688-L1690
> 
> 将代码块中`系名称`修改为`学院名称`。

没有效果，但是全局搜索确实找不到哪里还有 “系名称” 这个字符串，蒙了

**Comment by liyiwei979621500** [comment]
正确的修改地方应该是 htutthesis.cls的这两个地方

<img width="968" alt="image" src="https://user-images.githubusercontent.com/16919236/170467533-f9743882-ead4-49bf-9192-f5278fcbfd72.png">


<img width="896" alt="image" src="https://user-images.githubusercontent.com/16919236/170467507-c9d974b2-3752-4db0-91f7-32d296a115de.png">

**Comment by cyinen** [comment]
![image](https://user-images.githubusercontent.com/56926538/170482398-c1eb2a37-2b11-4a21-9fae-dca929d9798d.png)

学院名字太长了，这种怎么才能放在一行啊

**Comment by liyiwei979621500** [comment]
没这么讲究吧，我看以前的论文都没写人工智能学院

**Comment by LaureatePoet** [comment]
经过参考[合肥工业大学毕业设计手册2022.1.pdf](https://github.com/HFUTTUG/HFUT_Thesis/files/8790494/2022.1.pdf)
#35 已经修改此BUG。
