### ISSUE TITLE
如何加入作者签名和导师签名图片

### ISSUE THREAD

**Issue by codemonkey-1024** [HFUTTUG/HFUT_Thesis#32]
## 检查
- [ ] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
《合肥工业大学研究生学位论文写作规范》的 xx 文档的第xx页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{hfutthesis}
\begin{document}
abc
\end{document}
```

**Comment by LaureatePoet** [comment]
我个人比较推荐使用PDF编辑软件（例如：Adobe Acrobat DC）来插入签名图片。

----

如果实在想通过TeX编译插入，

编辑`hfutthesis.cls`文件
https://github.com/HFUTTUG/HFUT_Thesis/blob/32dd5e2fd21fd9918003f62a721828f35e5fe43a/hfutthesis.cls#L2354-L2406

在相应位置插入自己的签名即可。
```TeX
\includegraphics[⟨options⟩]{⟨filename⟩}
```
