### ISSUE TITLE
全部数学符号的命令参考的网站无法访问了

### ISSUE THREAD

**Issue by HanZhang1995** [HFUTTUG/HFUT_Thesis#38]
## 检查
- [ ] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
《合肥工业大学研究生学位论文写作规范》的 xx 文档的第xx页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{hfutthesis}
\begin{document}
abc
\end{document}
```
http://mirrors.ctan.org/macros/latex/contrib/unicode-math/unicode-math.pdf 和 http://mirrors.ctan.org/macros/latex/contrib/unicode-math/unimath-symbols.pdf 显示404了

**Comment by HowardZorn** [comment]
请直接从CTAN包详情页的链接中访问：https://ctan.org/pkg/unicode-math

你提到的这两个链接不保证稳定性。

另外可以考虑直接看texdoc.org的
