### ISSUE TITLE
博士论文致谢位置问题

### ISSUE THREAD

**Issue by ChrisChoi1305** [HFUTTUG/HFUT_Thesis#39]
博士论文中致谢应放在正文开头，即摘要之前。（学位办给的word模版是这么排的）
对应Tex文件main.tex中，部分内容需要修改一下。如：% 致谢页，硕博 请将该行注释去掉。和\input{chapters/acknowledgements.tex} % 致谢页，本科生 请将该行注释去掉。
总之就是一小小小问题，感谢！！

**Comment by l1teng** [comment]
@ChrisChoi1305 Thanks.
