### ISSUE TITLE
如何给封面添加页码？

### ISSUE THREAD

**Issue by huhengtong** [HFUTTUG/HFUT_Thesis#48]
## 检查
- [ ] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
“博士2份平装，要求从封面、序言、目录开始按照“1、2、3、. . . 、N ”自然数顺序编页码，学位论文中间的页码不编、保持原页码不变，最后在总页码上加上前面“封面、序言、目录等”内容多出的页数。”

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{hfutthesis}
\begin{document}
abc
\end{document}
```

**Comment by HowardZorn** [comment]
请给出对应的要求文档。

**Comment by huhengtong** [comment]
> 

“博士2份平装，要求从封面、序言、目录开始按照“1、2、3、. . . 、N ”自然数顺序编页码，学位论文中间的页码不编、保持原页码不变，最后在总页码上加上前面“封面、序言、目录等”内容多出的页数。”

**Comment by HowardZorn** [comment]
> > 
> 
> “博士2份平装，要求从封面、序言、目录开始按照“1、2、3、. . . 、N ”自然数顺序编页码，学位论文中间的页码不编、保持原页码不变，最后在总页码上加上前面“封面、序言、目录等”内容多出的页数。”

你需要把完整的需求文档，或者文档的链接上传上来。而不是单纯引用一句话
