### ISSUE TITLE
硕士使用学术类型专业报错

### ISSUE THREAD

**Issue by awmmmm** [HFUTTUG/HFUT_Thesis#49]
## 检查
- [ok] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ok] 已经将模板升级到了最新版
- [ok] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ok] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 11
- TeX 发行版：TeX Live 2022
- 模板类型： professional-master

## 描述问题
\documentclass[degree-type = professional]{hfutthesis}
这行代码加入后编译报错
截图：
![QQ图片20230302163233](https://user-images.githubusercontent.com/89187860/222374470-3fb3e2c6-705e-4fde-8219-703a24d4eb7e.png)

复现上述问题的代码：
```TeX

\documentclass[degree=master]{hfutthesis}
\documentclass[degree-type = professional]{hfutthesis}
```

**Comment by sikouhjw** [comment]
这是最最基础的基础知识问题，如果你要用 `professional` 类型，就把
```tex
\documentclass[degree=master]{hfutthesis}
```
改为
```tex
\documentclass[degree=professional]{hfutthesis}
```
而不是多加一行。

请你去阅读 LSHORT-ZH-CN 来入门，否则你将寸步难行。

**Comment by awmmmm** [comment]
好的哥
