### ISSUE TITLE
参考文献格式

### ISSUE THREAD

**Issue by zepinglee** [HFUTTUG/HFUT_Thesis#5]
我注意到你们的参考文献格式跟 [GB/T 7714—2015](http://www.cessp.org.cn/uploads/1/file/public/201607/20160708142456_8mqgu0dpgk.pdf) 并不完全一致。如果能把《写作规范》的示例整理为 `.bib` 格式的话（用于测试，参考 <https://github.com/CTeX-org/gbt7714-bibtex-style/blob/master/test/testbst/support/standard.bib>），我可以帮你们修改 bst。

另《写作规范》没有提到著者-出版年制的参考文献格式，可以把相关的 `*-author-year.*` 去掉。

**Comment by LaureatePoet** [comment]
感谢学长，我们会处理完`.bib`

其实我们一开始没有处理参考文献格式，是因为学校对我们学位论文参考文献格式并不重视（样可能对本科这），然后又因为今年发布的比较晚，没有硕博生实际使用，就没有去关注这个问题。

如果学长有空的话，不胜感激！😊

**Comment by litun5315** [comment]
re open #5

**Comment by XuYuQuan0713** [comment]
请问一下使用研究生的封面怎样修改，我照着说明还是不能把本科生毕业设计修改成别的
![QQ截图20211123115637](https://user-images.githubusercontent.com/67585051/142969311-d4e72a41-017c-4fd6-a470-d79099054efd.png)

**Comment by HowardZorn** [comment]
> 请问一下使用研究生的封面怎样修改，我照着说明还是不能把本科生毕业设计修改成别的

你好，有任何不相关问题请另开issue进行处理，不打乱之前的议题。

你只需在`main.tex`的`\documentclass`的`degree`选项中指定`master`，并重新编译即可
```
\documentclass[degree=master]{hfutthesis}
```

**Comment by XuYuQuan0713** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        好的，感谢
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                yqxu0713
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年11月23日 ***@***.***> 写道： 






请问一下使用研究生的封面怎样修改，我照着说明还是不能把本科生毕业设计修改成别的



你好，有任何不相关问题请另开issue进行处理，不打乱之前的议题。

你只需在main.tex的\documentclass的degree选项中指定master，并重新编译即可

\documentclass[degree=master]{hfutthesis}





—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LaureatePoet** [comment]
@ter-li 
补充 参考文献[GB/T 7714—2015](http://www.cessp.org.cn/uploads/1/file/public/201607/20160708142456_8mqgu0dpgk.pdf)格式 使用选项
