### ISSUE TITLE
documentclass 在添加 pdf 模式下，会导致页眉的偶数页无法出现 ”合肥工业大学研究生学位论文“。

### ISSUE THREAD

**Issue by A11en0** [HFUTTUG/HFUT_Thesis#51]
## 检查
- [x] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [x] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
《合肥工业大学研究生学位论文写作规范》的 xx 文档的第xx页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=master,pdf]{hfutthesis}
```

**Comment by LaureatePoet** [comment]
请注释or删除：
https://github.com/HFUTTUG/HFUT_Thesis/blob/6f0efdac293d749dbd65ce069cf97dbe19faebad/hfutthesis.cls#L400-L402

----
解决思路：
在`hfutthesis.cls`中搜索`pdf` 得知`output=electronic`（或者**通过认真阅读hfutthesis-doc.pdf**）得知`output=electronic`。进而搜索`electronic`共计找到四个结果，其中两个为`\if`，很容易可以判断是`hfutthesis.cls#L400-L402`
