### ISSUE TITLE
overleaf版本和最新版区别

### ISSUE THREAD

**Issue by jayus71** [HFUTTUG/HFUT_Thesis#56]
## 检查
- [x] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [x] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：Overleaf
- TeX 发行版：TeX Live 2022
- 模板类型：bachelor

## 描述问题
我是直接用的overleaf上的[模板](https://www.overleaf.com/latex/templates/hfut-thesis/ythwdqdkpvkp)开始编写的，但是今天在看issue的时候发现overleaf的版本似乎并不是跟GitHub上同步的，因为现在答辩迫在眉睫，重新开始用github上的模板有点来不及了，所以我想知道overleaf的版本和github上的有什么地方不同吗？

比如 #31 提到的问题，overleaf上的模板仍然存在，在修改了htutthesis.cls后问题才解决。

截图：

![image](https://github.com/HFUTTUG/HFUT_Thesis/assets/62584977/1f853efa-bd13-4607-86c9-d3285a9e0a1e)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{hfutthesis}
\begin{document}
abc
\end{document}
```

**Comment by zepinglee** [comment]
建议将 github 仓库的 .cls 文件覆盖 overleaf 的项目。

overleaf 上的项目虽然也是以 git 仓库的形式管理的，但是不能从本地 git push 上去，同步很不方便。

**Comment by jayus71** [comment]
收到 我替换一下
