### ISSUE TITLE
overleaf平台设置fontset时报错

### ISSUE THREAD

**Issue by jayus71** [HFUTTUG/HFUT_Thesis#57]
## 检查
- [x] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [x] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：Overleaf
- TeX 发行版：TeX Live 2022
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
> 华文字库和 Fandol 字库虽然不违反《规范》的要求，但是其字形跟中易字库有所差别，可能被审查老师认为格式不符合要求。所以建议在提交最终版前使用 Windows 平台的字体进行编译。

所以我在最开始设置了平台为windows，但是报错了，错误如下：

截图：
![image](https://github.com/HFUTTUG/HFUT_Thesis/assets/62584977/122b4cab-2ff9-4f65-a1eb-b84e49596d2c)

复现上述问题的代码：
```TeX
\documentclass[fontset=windows, degree=bachelor]{hfutthesis}
% degree      = doctor | master | bachelor
% degree-type = academic | professional
% language    = chinese | english
% fontset     = windows | mac | ubuntu | fandol
```

**Comment by jayus71** [comment]
update：是vscode的问题，目前问题未知，在使用miktex自带的texworks以后，选择如下编译引擎：
![image](https://github.com/HFUTTUG/HFUT_Thesis/assets/62584977/06283e8e-38ad-4561-8dd0-810a2512608f)
问题得以解决，插图，目录和引用都正常显示了，至此问题暂时解决，但是overleaf上的错误仍无法避免，上传simsun.ttc文件后又会报KaiTi错误，所以暂时放弃，后续修改在texworks上修改。

**Comment by zepinglee** [comment]
overleaf 没有 windows 的中易宋体（simsun）字体。

可以考虑：
1. 使用 texpage；
2. 上传全套的中易的宋黑楷仿字体。

**Comment by jayus71** [comment]
好的好的，不过29号就要答辩了，我先用着texworks凑合一下。

**Comment by LaureatePoet** [comment]
使用模板前建议先认真阅读hfutthesis-doc，另外本科生毕业论文完全不需要紧张。
