### ISSUE TITLE
2023届本科的页眉新标准

### ISSUE THREAD

**Issue by qdddz** [HFUTTUG/HFUT_Thesis#58]
## 检查
- [√] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [√] 已经将模板升级到了最新版
- [√] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [√] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 11
- TeX 发行版：MiKTeX 2.9.6753
- 模板类型：bachelor

## 描述问题
[《合肥工业大学2023届毕业设计（论文）》](https://co2.cnki.net/Details.html?dp=hfut&r=1685632096032&noticeId=109&typeId=909) 的文档的第24页要求 页眉的设置：位于正文部分，内容为“合肥工业大学本科毕业设计（论文）”。 而模板编译的结果是 “合肥工业大学毕业设计（论文）”

截图：
![image](https://github.com/HFUTTUG/HFUT_Thesis/assets/25915356/a60de9c1-3851-44ca-a128-422bcd441e07)

无需代码复现

**Comment by HowardZorn** [comment]
It's because that putting "合肥工业大学毕业设计（论文）" on the header is a historical requirement. Thank you for providing us with the newest documentation of requirements. We'll work on the newest documentation.
