### ISSUE TITLE
参考文献格式需要与源更新

### ISSUE THREAD

**Issue by Tariya321** [HFUTTUG/HFUT_Thesis#62]
## 检查
- [x] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [x] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2019
- 模板类型： bachelor

## 描述问题
参考文献中同时出现A和C标识符，老师要求修改为C。
查看了本项目中的bst格式，对比[引用源](https://github.com/zepinglee/gbt7714-bibtex-style/blob/master/gbt7714-numerical.bst)可见inproceedings类型不一致

截图：
![Pasted image 20240519154826](https://github.com/HFUTTUG/HFUT_Thesis/assets/108873513/d91d9b4b-286d-41e8-bbf4-9275944ce56e)

复现上述问题的代码：
无需代码

**Comment by zepinglee** [comment]
这里的差异是针对你们学校的《写作规范》的调整，详见 <https://github.com/HFUTTUG/HFUT_Thesis/commit/9daa1dd8ccfc87f88456a12a271767717e95e8cd>。最近官方的《写作规范》有更新吗？

**Comment by Tariya321** [comment]
fine，那就是老师的意见和官方意见目前不一致，不属于repo的问题
