### ISSUE TITLE
图录清单中不同章节的图片图录之间存在多余的间距

### ISSUE THREAD

**Issue by Tariya321** [HFUTTUG/HFUT_Thesis#63]
## 检查
- [x] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [x] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2019
- 模板类型：bachelor

## 描述问题
《合肥工业大学研究生学位论文写作规范》中图录清单各图录之间无特殊间距，不同章节之间不存在图片，然而编译结果中存在一个未知纵向间距。

截图：
![image](https://github.com/HFUTTUG/HFUT_Thesis/assets/108873513/34458bd1-8f3f-4133-96a5-eb57c9409517)

复现上述问题的代码：
无需代码

**Comment by Tariya321** [comment]
see [a solution](https://github.com/HFUTTUG/HFUT_Thesis/discussions/45#discussion-4396862) in the discussion.

**Comment by zepinglee** [comment]
这个可以使用 ctex 的 `lofskip` 和 `lotskip` 接口进行控制。

<img width="884" alt="Screenshot 2024-05-26 at 13 27 47" src="https://github.com/HFUTTUG/HFUT_Thesis/assets/12290822/6b60d7b3-91b4-4128-b822-491b05d293b1">
