### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by a-sisyphus** [HFUTTUG/HFUT_Thesis#7]
## 检查
- [ ] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
《合肥工业大学研究生学位论文写作规范》的 xx 文档的第xx页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{hfutthesis}
\begin{document}
abc
\end{document}
```
目前没有检查出问题，但是希望能作相应的改进

**Comment by sikouhjw** [comment]
你在说什么？

**Comment by LaureatePoet** [comment]
What?

**Comment by a-sisyphus** [comment]
能否在章节中增加一个章节介绍化学方程式或化学式的排版方法？

**Comment by HowardZorn** [comment]
您好，GitHub的issue是可以进行编辑的。前文显然忘记插入图片和详细描述。

> 
> 能否在章节中增加一个章节介绍化学方程式或化学式的排版方法？

感谢关注本项目，我们目前暂无这类计划，或许将来有人会去完善。若您为化学相关专业的同学，有自己的方案的话，可以向本仓库提出pull request，我们将会进行检查和受理。

**Comment by litun5315** [comment]
> 能否在章节中增加一个章节介绍化学方程式或化学式的排版方法？

Hi, @a-sisyphus 

Maybe this [tutorial](https://www.luogu.com.cn/blog/codesonic/chemistryinlatex) can help you. 

Best regards,
Teng Li
