### ISSUE TITLE
大佬，我想修改页眉，请问需要修改哪里啊

### ISSUE THREAD

**Issue by cyinen** [HFUTTUG/HFUT_Thesis#8]
## 检查
- [ ] 已经阅读《合肥工业大学研究生学位论文写作规范》或《合肥工业大学本科毕业设计（论文）工作实施细则》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `hfutthesis-doc.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/HFUTTUG/HFUT_Thesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / academic-master / professional-master / bachelor

## 描述问题
大佬，我想修改页眉，请问需要修改哪里啊

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{hfutthesis}
\begin{document}
abc
\end{document}
```

**Comment by sikouhjw** [comment]
https://github.com/HFUTTUG/HFUT_Thesis/blob/9b4e50f06ecf283e705c095cf8a7d2312d2fa50e/hfutthesis.cls#L1484-L1517

**Comment by cyinen** [comment]
感谢！已解决
