### ISSUE TITLE
编译错误信息为`LaTeX3 Error: The key 'ctex/tocdepth' is unknown and is being ignored. \begin{publications}`

### ISSUE THREAD

**Issue by XuYuQuan0713** [HFUTTUG/HFUT_Thesis#9]
## 编译环境
- 编译的系统： Windows 10
- TeX 发行版：TeX Live 2020
- 模板类型： professional-master 

## 描述问题
1.在win10的编译过程中出现错误，错误信息为**`LaTeX3 Error: The key 'ctex/tocdepth' is unknown and is being ignored. \begin{publications}`**
但是当我运行的时候虽然出错但是可以编译出main.pdf文件，并且在修改内容可以成功，但是还是会报错上述问题。
2.于是我尝试在linux环境下进行编译，当我编译执行make doc 命令可以生成hfutthesis-doc.pdf文件，但是当我make时，会出现错误：```
**make: *** No rule to make target 'hfutthesis-authoryear.bst', needed by 'main.pdf'.  Stop.**
```

截图：
![image](https://user-images.githubusercontent.com/67585051/157816950-80f0bd4e-4c65-43f6-92e3-b23fb1cebbae.png)

我想linux下错误可能与我没安装字体有关，但是make doc会使用默认字体可以成功，同时win10下的错误使我很纠结，到底是什么原因导致的

**Comment by LaureatePoet** [comment]
安装 `TeX Live 2021`

**Comment by XuYuQuan0713** [comment]
> Win10的问题 安装 `TeX Live 2021`可以解决。但可能是我们`.cls`没写好
> 
> 试试：将`hfutthesis.cls` L405
> 
> https://github.com/HFUTTUG/HFUT_Thesis/blob/9b4e50f06ecf283e705c095cf8a7d2312d2fa50e/hfutthesis.cls#L405
> 
> 修改为 `\LoadClass[UTF8,a4paper,scheme=plain,zihao=-4,fontset=none,heading = true]{ctexbook}[2017/04/01]`
> 
> 如果可以修复错误的话，反馈一下，下个版本更新`cls`

感谢你的回复😊，我刚才进行了修改，但是结果还是一样😭，我将尝试进行更新安装TeX Live 2021

**Comment by XuYuQuan0713** [comment]
你好，当我升级tex live后问题解决了，我也发现了一些警告，警告类型为：
![QQ截图20220312105117](https://user-images.githubusercontent.com/67585051/158001096-672dd5b5-8c3a-454d-8711-f49d8ac2b7da.png)
建议将例程中的floats.tex中所有的的\begin{table}[h]修改为\begin{table}[ht]，虽然这是一个例子，但是我认为一个好的开始有助于我们使用，最让人头疼的就是编译的警告或者错误。
希望这个仓库越来越好🌻

**Comment by zepinglee** [comment]
> 1.在win10的编译过程中出现错误，错误信息为**`LaTeX3 Error: The key 'ctex/tocdepth' is unknown and is being ignored. \begin{publications}`** 但是当我运行的时候虽然出错但是可以编译出main.pdf文件，并且在修改内容可以成功，但是还是会报错上述问题。 

`ctex` 的 `tocdepth` 是 2020-05-06 新增的功能，如果想要兼容旧版本的话可以使用 `\setcounter{tocdepth}{2}`。


> 2.于是我尝试在linux环境下进行编译，当我编译执行make doc 命令可以生成hfutthesis-doc.pdf文件，但是当我make时，会出现错误：``` **make: *** No rule to make target 'hfutthesis-authoryear.bst', needed by 'main.pdf'. Stop.**

Makefile 需要删掉 `-authoryear.bst`。

**Comment by LaureatePoet** [comment]
已修复。感谢 @zepinglee 大佬
